# Fast-Agent Configuration for AI Content Publisher
# This configuration defines MCP servers and model settings for parallel execution

mcp:
  servers:
    blackbox:
      command: "python"
      args: ["../bbai_mcp_server/blackbox_mcp_server.py"]
      env:
        BLACKBOX_API_KEY: "${BLACKBOX_API_KEY}"
        
    openai_server:
      command: "mcp-server-openai"
      args: []
      env:
        OPENAI_API_KEY: "${OPENAI_API_KEY}"
        
    claude_server:
      command: "mcp-server-anthropic"
      args: []
      env:
        ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"

# Model configurations for different AI providers
models:
  # Direct model access (no MCP server required)
  haiku:
    provider: anthropic
    model: claude-3-haiku-20240307
    
  sonnet:
    provider: anthropic
    model: claude-3-5-sonnet-20241022
    
  gpt4:
    provider: openai
    model: gpt-4o-mini
    
  gpt4o:
    provider: openai
    model: gpt-4o

# Default settings
defaults:
  model: haiku
  temperature: 0.7
  max_tokens: 2000